---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "libredesk.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "libredesk.labels" . | nindent 4 }}
type: Opaque
stringData:
  system-user-password: {{ .Values.systemUserPassword | quote }}

