---
{{- $secretName := printf "%s-sensitive" (include "libredesk.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "libredesk.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existingSecret $existingSecret.data (index $existingSecret.data "system-user-password") }}
  system-user-password: {{ index $existingSecret.data "system-user-password" }}
  {{- else }}
  system-user-password: {{ printf "%s%s%s%s" (randAlpha 8) (randNumeric 4) (shuffle "!@#$%&*" | trunc 2) (randAlphaNum 18) | shuffle | b64enc }}
  {{- end }}
